# Generated by Django 5.0.2 on 2024-10-03 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbaproj', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='feature_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
