# Generated by Django 5.1.1 on 2024-10-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbaproj', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Even Occur', 'verbose_name_plural': 'Events Occurs'},
        ),
    ]
