# Generated by Django 5.1.1 on 2024-10-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbaproj', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Event Occur', 'verbose_name_plural': 'Even Occurs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Time Period', 'verbose_name_plural': 'Time Periods'},
        ),
    ]
